### ISSUE TITLE
Will not build currently -- no field named union_

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [alexchandel/keystroke-rs#3]
Tried to use this library for a small project on Windows 10 and received the following error when compiling : 

error: structure `platform::winapi::INPUT` has no field named `union_`

I tried to link to this using both the crate name / version number and also manually direct it to the github page, both resulted in the same error. I imagine this probably has something to do with the way Rust attempts to access unions (A non native language element)? 

Looking online, the [documentation](https://censoredusername.github.io/dynasm-rs/runtime/winapi/winuser/struct.INPUT.html) and the error message's suggestion imply that the structure's field name should be u instead of union_ -- A seemingly easy fix I can try later.

**Comment by alexchandel** [comment]
It looks like the `winapi` crate changed its definition of the `INPUT` struct. The field used to be called `union_`.

**Comment by alexchandel** [comment]
Should be fixed in v0.0.3. Tell me if it's not.
